### ISSUE TITLE
how i bypass login  screen ? 

### ISSUE THREAD

**Issue by gkmaheshwari** [OSEHRA/popHealth#103]
we are working with API provided by Pophealth, from our EHR Module , we want when user click on button from our screen , we redirect to user on our pophealth url without asking login(no screen display for enter username/password.

**Comment by petercyli** [comment]
Hi gk,
You need to provide credential in the API calls to popHealth - see https://github.com/OSEHRA/popHealth/wiki/Uploading-QRDA-Cat-I-via-API
