### ISSUE TITLE
Patient not importing - Parse error

### ISSUE THREAD

**Issue by onizuka14** [OSEHRA/popHealth#148]
PopHealth doesn't import patient if it has a code nullFlavor="NA". Attached an example of XML generate by cypress.
Here an explanation on NullFavlor NA: [NullFlavor="NA"](http://www.cdapro.com/know/25021)
[1_Andy_Allen.zip](https://github.com/OSEHRA/popHealth/files/2361778/1_Andy_Allen.zip)

**Comment by petercyli** [comment]
Are you using the 2017 or the 2016 measure bundle?

 

The QRDA CAT1 release is different depending on the measure bundle used.

**Comment by onizuka14** [comment]
It is from the 2016 bundle

**Comment by petercyli** [comment]
Did you setup the popHealth with 2016 bundle?

**Comment by onizuka14** [comment]
No, it was 2017 bundle, my mistake
