### ISSUE TITLE
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.7.8

### ISSUE THREAD

**Issue by CaseyChester** [OSEHRA/popHealth#15]
I am following the installation instructions (ver 3) to stand up a demo server. When I get to the following command in step 7:

    bundle exec rake bundle:import[/home/pophealth/bundle-2.6.0.zip,false,false,'*',true,true] RAILS_ENV=development

I received the following:

WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.7.8
/home/iatric/popHealth/lib/tasks/sharding.rake:4: warning: class variable access from toplevel
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/pophealth/bundle-2.6.0.zip
/usr/local/rvm/gems/ruby-2.1.2/gems/health-data-standards-3.5.3/lib/health-data-standards/tasks/bundle.rake:41:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/health-data-standards-3.5.3/lib/health-data-standards/tasks/bundle.rake:41:in `open'
/usr/local/rvm/gems/ruby-2.1.2/gems/health-data-standards-3.5.3/lib/health-data-standards/tasks/bundle.rake:41:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => bundle:import
(See full trace by running task with --trace)

The greatest version of libxml2 distributed for Ubuntu Precise is 2.7.8. 

Please advise.

**Comment by smc-ssiddiqui** [comment]
Hi, it looks like your Linux home is on /home/iatric.

In the bundle:import task command, please change the location of the file to where you downloaded the bundle. So assuming the bundle was downloaded on to your home folder, you would run the following: 

    bundle exec rake bundle:import[/home/iatric/bundle-2.6.0.zip,false,false,'*',true,true] RAILS_ENV=development

**Comment by CaseyChester** [comment]
smc - I guess I just needed another set of eyes on it because I had not noticed the errant path in that command. At any rate, thanks for taking the time to help with such a trivial problem!
