### ISSUE TITLE
How to install bundle after getting an error?

### ISSUE THREAD

**Issue by onizuka14** [OSEHRA/popHealth#151]
I'm trying to install bundle from 2018, at first I got this error:
 'Index Key Too Long' 
So I used the mongodb command to fix this.
But now I get this error:
 'A bundle with version 2018.0.1 already exists in the database'

 But it is not sucessfull installed I only have the 2016 and 2017 bundles installed in my pophealth sucessfully. How I clean the 2018.0.1 from database so I can install it again ( without the Index error this time)

**Comment by petercyli** [comment]
The 2018 bundle is designed to work with the CQL based Cypress 4.0.  We are in the process of developing version 6.0 to handle 2018 bundle.  PopHealth version 5.1 will not be able to install 2018 bundle.
