### ISSUE TITLE
QRDA3 validation issue due to Performance Rate Cypress 2.6.1

### ISSUE THREAD

**Issue by dabimahesh** [OSEHRA/popHealth#21]
Hi

While test with latest Cypress 2.6.1 (Measure Bundle 2.6.0), it gives errors. Is there any way to fix those? nullFlavor has to be there along with precision handling. Any quick help will be appreciated. 

1.      Reported Performance Rate SHALL not have a precision greater than .000001
2.      Reported Performance Rate SHALL not have a precision greater than .000001
3.      Reported Performance Rate SHALL not have a precision greater than .000001
4.      Reported Performance Rate for Numerator 9ABAB074-B5D9-42B1-856C-AC8A91B847D9 should be NA
5.      Reported Performance Rate for Numerator 2919957C-F557-484C-A832-B7AF9F2D9685 should be NA

**Comment by truotaku** [comment]
I am having the same issue. Will be looking out for a solution to this!

**Comment by dabimahesh** [comment]
For time being can we comment of Performance Rate? Also the reporting period is getting wrong with respect to Cypress. Cypress expects 20130101000000 and not 20121231590000

Just let me know which config file I need to change locally so that I can have local fix.

Error: Reported Measurement Period should start on 20130101

Mahesh

**Comment by kghandi** [comment]
This appears to have been fixed in projectcypress/health-data-standards
But OSHERA/pophealth is still using health-data-standards 3.5.3 gem.

I had to work around this by directly modifying one of the files in the gem:
/usr/local/rvm/gems/ruby-2.1.5/gems/health-data-standards-3.5.3/templates/cat3/ _performance_rate.cat3.erb

This required changing read/write permissions on the file and the folder. I then replaced

        <value xsi:type="REAL" value="<%= population_group.performance_rate %>"/>

with 

    <% if !population_group.performance_rate.nan? %>
        <value xsi:type="REAL" value="<%= population_group.performance_rate.round(6) %>"/>
    <% else %>
        <value xsi:type="REAL" nullFlavor="NA"/>
    <% end %>

**Comment by petercyli** [comment]
We will update popHealth to use the 3.6.1 HDS gem in the next pull request.  Thanks for letting us know.

**Comment by cjohnsonal** [comment]
A pull request with the updated gem has been submitted [here](https://github.com/OSEHRA/popHealth/pull/28).
