### ISSUE TITLE
Date Calculation Issue in popHealth - Wrong Denominator.

### ISSUE THREAD

**Issue by sgargbugreporter** [OSEHRA/popHealth#23]
We have popHealth installed from github. The versions installed are:

```
popHealth commit: 3fd494
last tag: v3.0.0.rc1
bundle 2.6.0
```

The issue I am having is with calculation of Blood Pressure measure (CMS165v3) for a time period ending earlier than 2nd August.

A video showing this issue is available at: https://youtu.be/LRIDBCvsWoU

# Specifics of the issue

We have created 10 patients, all of whose Blood Pressure starts off as uncontrolled. The data used for this testing is available at: https://drive.google.com/file/d/0B80jMILLPf0vTm1Ra3pVR0NvZVU/view?usp=sharing

Some of the details pertaining to these 10 patients are:

Patient Name	| Last Encounter Date | Controlled (Y/N)?
------------------- | --------------------------- | -------------------------
Heart_Adult_1 Controlled | 09/20/2013 | Y
Heart_Adult_2 Controlled | 09/05/2013 | Y
Heart_Adult_3 Controlled | 08/20/2013 | Y
Heart_Adult_4 Controlled | 12/20/2013 | Y
Heart_Adult_5 Controlled | 12/20/2013 | Y
Heart_Adult_1 Uncontrolled | 12/20/2013 | N
Heart_Adult_2 Uncontrolled | 12/20/2013 | N
Heart_Adult_3 Uncontrolled |12/20/2013  | N
Heart_Adult_4 Uncontrolled | 07/04/2013 | N
Heart_Adult_5 Uncontrolled | 06/04/2013 | N

Based on the above data, the following lists the expected values and the actual values we get from popHealth

End Date	| Expected Numerator | Expected Denominator | popHealth	Numerator | popHealth   Denominator | Result as Expected?
-------------- | ----------------- | ----------- | --------- | ----------- | -------------							
12/31/2013 | 5	 | 10 | 5 | 10| Y				
09/30/2013 | 3	 | 10 | 3 | 10| Y	
09/15/2013 | 2	 | 10 | 2 | 10| Y			
09/01/2013 | 1	 | 10 | 1 | 10| Y		
08/21/2013 | 1	 | 10 | 1 | 10| Y		
08/20/2013 | 0	 | 10 | 0 | 10| Y		
08/19/2013  | 0 | 10 | 0 | 10| Y	
08/15/2013  | 0 | 10 | 0 | 10| Y	
08/10/2013  | 0 | 10 | 0 | 10| Y	
08/03/2013  | 0 | 10 | 0 | 10| Y	
08/02/2013  | 0 | 10 | 0 | 10 | Y	
08/01/2013  | 0 | 10 | 0 | 0 | N		
07/01/2013  | 0 | 10 | 0 | 0 | N		
06/15/2013  | 0 | 10 | 0 | 0 | N		

# The specific question(s)

1. Why does the Denominator become '0' when the end date is before August 02? The denominator of the population should remain the same at 10.
2. What is the magic in August 2?

A video showing this issue is available at: https://youtu.be/LRIDBCvsWoU

**Comment by rdingwell** [comment]
I haven't investigated this fully but from a brief look at your video you are changing the measure period used for calculation and there are a number of constraints in the IPP that will be effected regarding changes like that. If you look at the logic below it is concerned with the person age at the start of the measure period or whether they had a Hypertension diagnosis in the first 6 months of the period or before the measure period.  

If I had to guess It would be that the patients are probably failing this part of the IPP.

AND:
    OR: "Occurrence A of Diagnosis, Active: Essential Hypertension" <= 6 month(s) starts after start of    "Measurement Period"
    OR:
       AND: "Occurrence A of Diagnosis, Active: Essential Hypertension" starts before start of "Measurement Period"
       AND NOT: "Occurrence A of Diagnosis, Active: Essential Hypertension" ends before start of "Measurement Period"

Or they did not end up with a qualifying encounter during the Measure Period. 

On a side note, the CQMs define their measure period to be 01/01/xxxx - 12/31/xxxx , I'm not sure moving it around like that is the right idea.  If I recall correctly the idea of reporting period was simply to allow reporting on patients that had been seen in a particular 3 month period of time, not that the measure period was adjusted to that period of time.

**Comment by petercyli** [comment]
The reason that patient weren't inlcude in the 06/15, 07/01, and 08/01 end date is the condition - "Occurrence A of Diagnosis, Active: Essential Hypertension" <= 6 month(s) starts after start of "Measurement Period"
If you look at the patient records, all had diagnosis of hypertension on 03/01/2013.  As you change the end date, it pushes the start date back by one year from the end date.  So a end date of 08/01/2013 would mean a start date of 08/01/2012.  If you use the (<=6 month(s) condition from the start  date, then the 03/01/2013 active hypertension would start to fall out of the 6 month window.  Now it seems that calculation of the <= 6 months is actually more like <= 7 months, but I don't know the exactly algorithm used for determining <= 6 month(s).

rdingwell's comment about the measure period is correct in that the CQMs as defined by ONC all assumes a one year calendar year; however, based on community's input, we have opt to allow user to set the measurement period to any arbitrary period.and dates,  With this flexibility, there is a prices to pay in the sense that if user doesn't understanding the logic of the particular CQM, then it is likely that one can easily misinterpret the result, The CQM calculation may be correct, but is it clinically meaningful still? **so buyer's be aware** if you deviate from the standard ONC sanctioned measurement period.
