### ISSUE TITLE
Error in install wiki for v4.0

### ISSUE THREAD

**Issue by sergekh42** [OSEHRA/popHealth#25]
In Step 13 when configuring apache.

The config for pophealth's directory location are incorrect.

/etc/apache2/sites-available/pophealth

These lines should be changed:

DocumentRoot /home/pophealth/popHealth/public
\<Directory /home/pophealth/popHealth/public>

to:

DocumentRoot /home/ubuntu/popHealth/public
\<Directory /home/ubuntu/popHealth/public>

**Comment by petercyli** [comment]
This really depends on where the pophealth is installed.  I will add a line to let user know you will need to modify the script accordingly to where pophealth is installed.

**Comment by petercyli** [comment]
Done
