### ISSUE TITLE
Assets Failing to Load

### ISSUE THREAD

**Issue by kghandi** [OSEHRA/popHealth#26]
I have just installed popHealth using Installation v4.0 instructions. 
popHealth commit: 90277b
last tag: v4.0.0
bundle 2.6.0

But many of the icons seem to be missing when viewing in Chrome. The Chrome Console displays following load errors:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Medium/Roboto-Medium-webfont.woff 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Medium/Roboto-Medium-webfont.ttf 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Regular/Roboto-Regular-webfont.ttf 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Thin/Roboto-Thin-webfont.woff 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Bold/Roboto-Bold-webfont.woff 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Thin/Roboto-Thin-webfont.ttf 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/Roboto-Bold/Roboto-Bold-webfont.ttf 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.98.161/assets/font-awesome/fonts/fontawesome-webfont.ttf?v=4.0.3 

By contrast, when I run in Development mode, I do see the icons without problem.

Incidentally, when precompiling the assets, the following warnings appeared:

pophealth@ubuntu:~/popHealth$ rake assets:precompile
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
/home/pophealth/popHealth/lib/tasks/sharding.rake:4: warning: class variable access from toplevel

I can fix some of the icons by copying ~/popHealth/vendor/assets/components/font-awesome
to ~/popHealth/public/assets/font-awesome
and precompiling the assets again. But I suspect there must be a better solution.

**Comment by petercyli** [comment]
The 
$ rake assets:precompile
is missing additional arguments.  It should have been
$ rake assets:precompile RAILS_ENV=production RAILS_RELATIVE_URL_ROOT=/home/popheatlh/popHealth

I've updated the documentation.
By the way, the development setup runs directly from the code base without compilation, hence, slower performance.  That's why you didn't see the same issue when running in the "development" setup. 

Thanks.

**Comment by kghandi** [comment]
Thank you. That resolved the issue.
