### ISSUE TITLE
QRDA3 file does not contain measure data

### ISSUE THREAD

**Issue by kghandi** [OSEHRA/popHealth#27]
I have just installed popHealth using Installation v4.0 instructions. 
popHealth commit: 90277b
last tag: v4.0.0
bundle 2.6.0

I have been testing with CMS122v3.  I am now able to generate QRDA Cat3 files. The generated file does contain an entry for the CMS122v3 measure, but does not actually have the data for Initial Population, Denom, Numer, etc. even though the data is displayed in the UI.

I am a complete beginner with debugging Ruby. But here is what I see... populations and population_groups in the results object are empty:

    12: def export(measures, header, effective_date, start_date, end_date, filter=nil,test_id=nil)
    13:   results = {}
    14:   measures.each do |measure|
    15:     results[measure['hqmf_id']] = HealthDataStandards::CQM::QueryCache.aggregate_measure(measure['hqmf_id'], effective_date, filter, test_id)
    16:   end
    => 17:   @rendering_context.render(:template => 'show', 
    18:                             :locals => {:measures => measures, :start_date => start_date, 
    19:                                         :end_date => end_date, :cat1_renderer => @cat1_renderer,
    20:                                         :results => results,
    21:                                         :header=>header})
    22: end

[15] pry(#<HealthDataStandards::Export::Cat3>)> measures
=> #<Mongoid::Criteria
  selector: {"$or"=>[{"sub_id"=>nil}, {"sub_id"=>"a"}], "hqmf_id"=>{"$in"=>["40280381-4555-E1C1-0145-90AC70DE2C73"]}}
  options:  {}
  class:    HealthDataStandards::CQM::Measure
  embedded: false>

[16] pry(#<HealthDataStandards::Export::Cat3>)> results
=> {"40280381-4555-E1C1-0145-90AC70DE2C73"=>
  #<HealthDataStandards::CQM::AggregateCount:0x000000097de7f0
   @measure_id="40280381-4555-E1C1-0145-90AC70DE2C73",
   @population_groups=[],
   @populations=[]>}

**Comment by kghandi** [comment]
I have found a solution...

The file in popHealth/lib/hds/query_cache.rb is overriding the aggregate_measure method of query_cache.rb which is in health-data-standards gem. There are two problems.

1. The extra parameter effective_start_date does not match the calling routine.
2. The test_id filter does not seem to be working correctly.

If I change:
    def self.aggregate_measure(measure_id, effective_date, effective_start_date, filters=nil, test_id=nil)
        query_hash = {'effective_date' => effective_date, 'effective_start_date' => effective_start_date, 'measure_id' => measure_id,
                      'test_id' => test_id}
      
To
      def self.aggregate_measure(measure_id, effective_date, filters=nil, test_id=nil)
        query_hash = {'effective_date' => effective_date, 'measure_id' => measure_id}

The problem with missing performance data is fixed.
I am not sure if this is the appropriate patch though.

**Comment by petercyli** [comment]
Thanks a lot.  We will create a emergency pull request early next week to get this problem fixed as soon as possible.  Looks like the "flexible reporting period" pull request created this issue.

**Comment by cjohnsonal** [comment]
Quick update - a pull request to resolve this issue has been submitted [here](https://github.com/OSEHRA/popHealth/pull/28).

**Comment by petercyli** [comment]
Fixed with pull request https://github.com/OSEHRA/popHealth/pull/28
