### ISSUE TITLE
popHealth 4.0.2 Production environment - unable to import patients

### ISSUE THREAD

**Issue by sgargbugreporter** [OSEHRA/popHealth#42]
I have set up an Ubuntu 14.04 VM with popHealth 4.0.2 with a production setup as given in: https://github.com/OSEHRA/popHealth/wiki/Installation-v4.0

I am unable to load any patients. Even after selecting the zip file and pressing upload, I am not getting any patients loaded.

This is what I get in the production.log:
Started PUT "/admin/upload_patients" for 10.159.93.40 at 2016-04-06 00:13:45 -0400
Processing by AdminController#upload_patients as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"MTxfOxl/1kWjST+SV7c1C3hju8xD5t+xjWPcxUbdV2I=", "file"=>#<ActionDispatch::Http::UploadedFile:0x0000000483a528 @tempfile=#<Tempfile:/tmp/RackMultipart20160406-12650-u65cq3>, @original_filename="patient_qrda_pophealth.zip", @content_type="application/zip", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"patient_qrda_pophealth.zip\"\r\nContent-Type: application/zip\r\n">, "commit"=>"Upload"}
Redirected to http://10.159.93.234/admin/patients
Completed 302 Found in 37ms
Started GET "/admin/patients" for 10.159.93.40 at 2016-04-06 00:13:45 -0400
Processing by AdminController#patients as HTML
  Rendered admin/patients.html.erb within layouts/application (2.5ms)
  Rendered shared/_header.html.erb (2.0ms)
Completed 200 OK in 17ms (Views: 6.7ms)
Started GET "/api/admin/patients/count" for 10.159.93.40 at 2016-04-06 00:13:50 -0400
Processing by Api::Admin::PatientsController#count as JSON
Completed 200 OK in 15ms (Views: 0.4ms)

Any ideas on where to look for debugging this.

Thanks,
Sachin

**Comment by lrasmus** [comment]
Sachin - is your background processor running (rake jobs:work)?  Given that the PUT message here is successful, that to me seems the first place to look.

**Comment by sgargbugreporter** [comment]
Thanks, Luke. The backgroudn processor was not working. Oversight  on my part :(
