### ISSUE TITLE
Unable to download measure bundle

### ISSUE THREAD

**Issue by mobsix** [OSEHRA/popHealth#58]
The contrib/install_pophealth.sh is pointing to demo.projectcypress.org, which does not resolve, on line 578:

`curl -s -u ${nlm_user}:${nlm_passwd} http://demo.projectcypress.org/bundles/bundle-latest.zip -o ../bundle-latest.zip" pophealth`

~/popHealth$ bundle exec rake pophealth:download_update_install version=2.6.0 RAILS_ENV=production
/home/clohl/popHealth/lib/tasks/sharding.rake:4: warning: class variable access from toplevel
NLM Username?: c#######
NLM Password?:
Downloading and saving bundle-2.6.0.zip to /home/clohl/popHealth/bundles
An error occured while downloading the bundle
rake aborted!
Errno::ETIMEDOUT: Connection timed out - connect(2) for "demo.projectcypress.org" port 80

**Comment by lrasmus** [comment]
Sure enough, I can't get to it either.  I didn't realize they were decommissioning it.  Looking at the Cypress v3 instructions, they are now using https://cypressdemo.healthit.gov/measure_bundles/ for bundles.  However, I tried the version they have there and get an error during import.  I think we need to fix that for the new bundles and update where the rake task is pulling from.

**Comment by petercyli** [comment]
Hi Luke,

Can you create a pull request and update ./lib/tasks/pophealth.rake line 102 with the proper url:
bundle_uri = "http://demo.projectcypress.org/bundles/#{@bundle_name}"
Change to:
bundle_uri = " https://cypressdemo.healthit.gov/measure_bundles/#{@bundle_name}"
I did a diff between the old bundle-2.6.0.zip and what is on the new cypress site, and there were no differences. 

I believe this will fix the installation problem.
Thanks.

**Comment by lrasmus** [comment]
Thanks for doing that validation Peter, the error may just have been something in my local code.  Just sent a PR through.

**Comment by petercyli** [comment]
Thanks for creating the PR #59.  I just did a test, and the installation worked fine.

The only thing is that the Travis CI is putting out an error:Gem Load Error is: undefined method `field' for QME::QualityReport:Class, not sure what is causing that.

**Comment by lrasmus** [comment]
Let me look, I thought I had fixed that in PR #57 but I can see it failing locally now too.

**Comment by lrasmus** [comment]
@petercyli I think we're back to normal... there were some changes intended for #57 that were missing and re-applied.  Travis came back as passing for this PR now.

**Comment by petercyli** [comment]
Thanks.

**Comment by mobsix** [comment]
Everything imported fine on our dev & QA systems.  Thanks!
