### ISSUE TITLE
Patient Demographics - seed task

### ISSUE THREAD

**Issue by siddiqus** [OSEHRA/popHealth#7]
Currently for popHealth's database, the collections for Race, Ethnicity, and Languages are not included. This requires a rake task to seed the database which was included in V2. The following branch reintroduces the task to include patient demographics information in the patient summary page.

https://github.com/smc-ssiddiqui/popHealth/tree/demographics

The demographic codes are imported during step 8 of the installation https://github.com/OSEHRA/popHealth/wiki/Installation using the 'rake db:seed' task.

**Comment by petercyli** [comment]
Fixed with pull request https://github.com/OSEHRA/popHealth/pull/30
