### ISSUE TITLE
Flexible Reporting Period Bug

### ISSUE THREAD

**Issue by npm526** [OSEHRA/popHealth#79]
When adjusting the reporting period, there are patients that are appearing in measures when they should not.

I have attached a sample CCD Below. In this sample, this patient has a diagnosis of hypertension and encounters on 20160704 and 20170101. However, when adjusting the reporting period to 9/1/2016-11/30/2016, this patient appears in the denominator even though there was no encounter during this reporting period. 

[sample.zip](https://github.com/OSEHRA/popHealth/files/748694/sample.zip)

**Comment by lrasmus** [comment]
How did you import your measures?  There is a special routine that injects flexible reporting period code into the measure logic.  I ran into a problem where I loaded measures in a way that didn't go through that routine.

**Comment by npm526** [comment]
Does the installation guide include the special instructions? I will try to reload the measure bundle using the instructions on the installation guide.

**Comment by npm526** [comment]
It looks like that fixed the issue.

Thanks!
Nick
