### ISSUE TITLE
Install step 7 results in a Syntax Error

### ISSUE THREAD

**Issue by etiology** [OSEHRA/popHealth#88]
Hi all,

I'm getting stuck at [step 7 of the install](https://github.com/OSEHRA/popHealth/wiki/Installation-v4.0#7-import-the-measure-bundle) with a ```SyntaxError``` in [providers_controller.rb](https://github.com/OSEHRA/popHealth/blob/8b6c8bd6bcb7715ddd1a72ae941104d1274ad81a/app/controllers/api/providers_controller.rb#L163-L169).

The command I'm running is:
```bundle exec rake pophealth:download_update_install version=2.6.0 RAILS_ENV=production```

Here is the error:
```
rake aborted!
SyntaxError: /osehra/popHealth/app/controllers/api/providers_controller.rb:163: syntax error, unexpected ':', expecting =>
        query={"addresses" => {"$elemMatch" => {"$or":[
                                                      ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:164: syntax error, unexpected ':', expecting =>
            {"city":/#{x}/i},
                    ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:164: syntax error, unexpected '}', expecting keyword_end
            {"city":/#{x}/i},
                            ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:165: syntax error, unexpected ':', expecting =>
            {"street":/#{x}/i},
                      ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:165: syntax error, unexpected '}', expecting keyword_end
            {"street":/#{x}/i},
                              ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:166: syntax error, unexpected ':', expecting =>
            {"state":/#{x}/i},
                     ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:166: syntax error, unexpected '}', expecting keyword_end
            {"state":/#{x}/i},
                             ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:167: syntax error, unexpected ':', expecting =>
            {"zip":/#{x}/i},
                   ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:167: syntax error, unexpected '}', expecting keyword_end
            {"zip":/#{x}/i},
                           ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:168: syntax error, unexpected ':', expecting =>
            {"country":/#{x}/i}
                       ^
/osehra/popHealth/app/controllers/api/providers_controller.rb:168: syntax error, unexpected '}', expecting keyword_end
/osehra/popHealth/config/environment.rb:5:in `<top (required)>'
/osehra/popHealth/lib/tasks/admin.rake:1:in `<top (required)>'
/osehra/popHealth/Rakefile:15:in `<top (required)>'
(See full trace by running task with --trace)
```

**Any suggestions or thoughts?**

Side Note:  I signed up for a NLM account like this step said but I don't understand where this fits into this step.  Also from the nih page I didn't see a place for NLM VSAC Services.  Is there an environment variable that I need to set so that the app can connect to the NLM VSAC API?

**Comment by etiology** [comment]
It's looking like this fork's wiki is missing instructions that can be found on the [original project](https://github.com/pophealth/popHealth/wiki/Installation#7-import-the-measure-bundle).  Particularly step 7 and the command to download the NLM VSAC service files.

**Comment by petercyli** [comment]
Can you be a bit more clear as to what is wrong with the following command delineated in Step 7 of the instruction:

bundle exec rake pophealth:download_update_install version=2016 RAILS_ENV=production

Thanks.

**Comment by etiology** [comment]
Sure.

In this project's Wiki the steps for 7 mention the NLM account requirements but then go straight into the **bundle** command.  The bundle command is failing and I can only assume that it's because the projectcypress.org bundle file hasn't been downloaded yet.  

The original project has this listed setp listed prior to running the ```bundle exec rake ...``` command:


``` bash
curl -u NLM_USERNAME:NLM_PASSWORD http://demo.projectcypress.org/bundles/bundle-latest.zip -o ../bundle-latest.zip
```

**Comment by petercyli** [comment]
Looking at your instruction.  Looks like you are using popHealth v4.0 instruction instead of the v5.0.  Are you planning to use popHealth v4.0?

**Comment by etiology** [comment]
I might have linked the wrong Install instructions, however the [wiki for v5.0](https://github.com/OSEHRA/popHealth/wiki/Installation-v5.0) is also missing the step to download the actual dataset used by the bundle command.

When I run the command in step 7 for v5.0 I get a syntax error.  
 1. Should I assume it is because the NLM file needs to downloaded so that it is locally available to this command?
  2. In version 5.0 does the bundle command download the file without my account credentials?

I assume that the curl command to download the NLM file is required but I'm not at a point where I can verify this right now.  I'll have to come back to it and see if I can get it working.  If there is a missing step in the install instructions for 5.0, and let's assume I am able to get past it, then I intent to submit a pull request for fixing the install instructions to make it easier on the next person.

**Comment by petercyli** [comment]
The rake command - pophealth:download_update_install will first ask for the NLM credential.  When accepted, it will automatically download the measure bundle specified by the "version" argument.  After the download, it will extract the downloaded measure bundle zip file, transform the measure bundle to work with flexible reporting period, and load the bundle into the database.   Your problem is with the earlier steps.  Somehow the popHealth codebase has not been installed correctly.  Some components are either missing or not correctly installed, which is giving you error when running the command.  Please check your console output for warnings and errors after you have run the "bundle install" command in Step 6 - Downloading PopHealth Source Code.

**Comment by etiology** [comment]
Ok. That helps point me in the right direction. I'll start with that
