### ISSUE TITLE
Communications entry in QRDA Cat1 is not being updated

### ISSUE THREAD

**Issue by chelope** [OSEHRA/popHealth#95]
I found a scenario where communications entry is not being updated in PopHealth. Below the steps:

1) I uploaded in PopHealth a patient with 2 encounters and 1 procedure.
2) I uploaded the same patient loaded before but including a communications entry in QRDA Cat1. When I reviewed the data in "record" collection in PopHealth database the communication entry was not included.

Fix:
In order to include communications entry as valid section to be updated we should include communications section in the class hds/record.rb

Valid_Sections = [:allergies, :conditions, :encounters, :immunizations, :medications, :procedures, :results, :vital_signs, :socialhistories, :communications]

Please let me know if you agree with this change.

**Comment by petercyli** [comment]
Agreed.  Please issue a pull request.

Thanks.

**Comment by chelope** [comment]
Change has been merged into master branch

**Comment by dabimahesh** [comment]
While communication gets exported, the node <sdtc:inFulfillmentOf1 typeCode="FLFS"> which is referenced with Intervention is not getting exported.

Thanks
Mahesh
